### PR TITLE
Normative: avoid double construction of `this` value

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #35. Requires consensus.

### CODE REVIEW

**Comment by michaelficarra** [comment]
This has consensus.

**Comment by Ms2ger** [comment]
This will likely need some test changes, including perhaps https://github.com/tc39/test262/blob/88a2f0dcd1df45635ebb20004ef5e5b7038f56bc/test/built-ins/Array/fromAsync/this-constructor.js

**Comment by michaelficarra** [comment]
Ping @js-choi. It's been over a month. Can you merge this? I don't have the required permissions.

**Comment by michaelficarra** [comment]
Ping @js-choi one last time. It's been over 3 months now. If you're not available to continue championing it, I'm going to request to take over this proposal.

**Comment by js-choi** [comment]
My sincere apologies for the neglect here. I’ve merged it in.

**Comment by michaelficarra** [comment]
@js-choi I don't see any recent commits on `main`: https://github.com/tc39/proposal-array-from-async/commits/main

**Comment by js-choi** [comment]
Fixed, sorry.

**Pull request merged**
